name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: Test
      run: |
        npm install -g truffle
        npm install -g ganache-cli
        npm install
        ganache-cli -d --chainId 1 -q -u 0x0C4DeC4c53a9c6EbF7877EE0fFEc663645566345 -p 18545 &
        sleep 5
        truffle test --network development --show-events

  # Tests-Flow:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Test
  #     run: |
  #       sh -ci "$(curl -fsSL https://storage.googleapis.com/flow-cli/install.sh)"
  #       cd flow
  #       flow project start-emulator &
  #       sleep 5
  #       flow accounts create --key f262c25a256f488e62273a2171065c9ee406b48186938626d10645a42121e3d53fe1b4a95cb3ae71614bcd5a4e634f9294483d820e6c8cb60a6687421ff2d1ff --results
  #       flow project deploy
  #       flow transactions send -c mint.cdc --results
  #       flow transactions send -c set_env.cdc --results
  #       flow transactions send -c setup_account.cdc --results -s acc1
  #       flow transactions send -c transfer.cdc --results
  #       flow transactions send -c set_env.cdc --results -s acc1
  #       flow transactions send -c transfer_back.cdc --results -s acc1
  #       flow transactions send -c set_env.cdc --results
